--ozone-platform-hint=auto
--enable-features=UseOzonePlatform,WaylandWindowDecorations,WaylandTextInputV3,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,ScrollUnification,WebRTCPipeWireCapturer
--disable-features=VulkanUsePlatformWindowAsRotationNotSupported
--disable-gpu-sandbox
--enable-zero-copy
--enable-gpu-rasterization
--canvas-oop-rasterization
--disable-font-subpixel-positioning
--disable-threaded-scrolling
